replicaCount: 1

image:
  repository: 654654229415.dkr.ecr.us-east-1.amazonaws.com/taskflow-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

env:
  MONGO_URI: mongodb://mongo:27017/taskdb
serviceAccount:
  create: true
